# Generated by Django 4.2.1 on 2026-04-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studdoc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='form_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('material-help', 'Материальная помощь'), ('profcom', 'Профком'), ('academic', 'Академические вопросы'), ('social', 'Социальные льготы'), ('certificate', 'Справка об обучении'), ('academic_leave', 'Академический отпуск')], max_length=50),
        ),
    ]
