# Generated by Django 4.2.1 on 2026-04-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studdoc', '0002_request_form_data_alter_request_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('material', 'Материальная помощь'), ('profkom', 'Профком'), ('certificate', 'Справка об обучении'), ('academic_leave', 'Академический отпуск')], max_length=50),
        ),
    ]
