# Generated by Django 4.2.1 on 2026-04-14 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studdoc', '0003_alter_request_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='category',
            field=models.CharField(choices=[('material-help', 'Материальная помощь'), ('profcom', 'Профком'), ('academic', 'Академические вопросы'), ('social', 'Социальные льготы')], max_length=50),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='file',
            field=models.FileField(upload_to='templates/', validators=[django.core.validators.FileExtensionValidator(['docx'])]),
        ),
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('material-help', 'Материальная помощь'), ('profcom', 'Профком'), ('academic', 'Академические вопросы'), ('social', 'Социальные льготы')], max_length=50),
        ),
    ]
