# Generated by Django 4.2.1 on 2026-04-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studdoc', '0004_alter_documenttemplate_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
    ]
