# Generated by Django 4.2.1 on 2026-05-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studdoc', '0005_userprofile_first_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('staff', 'Сотрудник деканата'), ('profcom', 'Сотрудник профкома'), ('admin', 'Администратор')], default='student', max_length=20),
        ),
    ]
