# Generated by Django 4.2.1 on 2026-05-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studdoc', '0006_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении в деканате'), ('in_profcom', 'На рассмотрении в профкоме'), ('profcom_approved', 'Одобрено профкомом'), ('profcom_rejected', 'Отклонено профкомом'), ('approved', 'Полностью одобрено'), ('rejected', 'Отклонено окончательно')], default='pending', max_length=20),
        ),
    ]
