# Generated by Django 4.2.1 on 2026-05-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studdoc', '0009_alter_request_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='category',
            field=models.CharField(choices=[('material-help', 'Материальная помощь'), ('profcom', 'Заявление о вступлении в Профком'), ('academic', 'Академический отпуск'), ('social', 'Социальные льготы (ПГАС)'), ('dismissal', 'Отчисление по собственному желанию'), ('personal_data', 'Согласие на обработку персональных данных')], max_length=50),
        ),
    ]
